---
- name: copy package to server k8sregistrydev
  copy:
    src: /root/Ansible/K8s/images/registry.tar.gz
    dest: /root/k8s/images
    follow: yes
  when: inventory_hostname in groups['k8smtdev']
- name: install docker registry
  args:
    chdir: /root/k8s/images
  command: "docker load -i registry.tar.gz"
  when: inventory_hostname in groups['k8smtdev']
- name: run images k8sregistrydev:5000
  command: "docker run -d -p 5000:5000 --restart=always --name registry registry:2"
  when: inventory_hostname in groups['k8smtdev']
